services:

  springapp:
    build: SpringApp
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - PROD_DB_PORT=${PROD_DB_PORT}
      - PROD_DB_NAME=${PROD_DB_NAME}
      - PROD_DB_USERNAME=${PROD_DB_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}


  database:
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${PROD_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306

volumes:
  db-data:
